/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestContract } from "./TestContract";
export * as factories from "./factories";
export { TestContract__factory } from "./factories/TestContract__factory";
