/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace StandardBounties {
  export type FulfillmentStruct = { fulfillers: string[]; submitter: string };

  export type FulfillmentStructOutput = [string[], string] & {
    fulfillers: string[];
    submitter: string;
  };

  export type ContributionStruct = {
    contributor: string;
    amount: BigNumberish;
    refunded: boolean;
  };

  export type ContributionStructOutput = [string, BigNumber, boolean] & {
    contributor: string;
    amount: BigNumber;
    refunded: boolean;
  };

  export type BountyStruct = {
    issuers: string[];
    approvers: string[];
    deadline: BigNumberish;
    token: string;
    tokenVersion: BigNumberish;
    balance: BigNumberish;
    hasPaidOut: boolean;
    fulfillments: StandardBounties.FulfillmentStruct[];
    contributions: StandardBounties.ContributionStruct[];
  };

  export type BountyStructOutput = [
    string[],
    string[],
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    boolean,
    StandardBounties.FulfillmentStructOutput[],
    StandardBounties.ContributionStructOutput[]
  ] & {
    issuers: string[];
    approvers: string[];
    deadline: BigNumber;
    token: string;
    tokenVersion: BigNumber;
    balance: BigNumber;
    hasPaidOut: boolean;
    fulfillments: StandardBounties.FulfillmentStructOutput[];
    contributions: StandardBounties.ContributionStructOutput[];
  };
}

export interface TestContractInterface extends utils.Interface {
  functions: {
    "acceptFulfillment(address,uint256,uint256,uint256,uint256[])": FunctionFragment;
    "addApprovers(address,uint256,uint256,address[])": FunctionFragment;
    "addIssuers(address,uint256,uint256,address[])": FunctionFragment;
    "bounties(uint256)": FunctionFragment;
    "callStarted()": FunctionFragment;
    "changeApprover(address,uint256,uint256,uint256,address)": FunctionFragment;
    "changeBounty(address,uint256,uint256,address[],address[],string,uint256)": FunctionFragment;
    "changeData(address,uint256,uint256,string)": FunctionFragment;
    "changeDeadline(address,uint256,uint256,uint256)": FunctionFragment;
    "changeIssuer(address,uint256,uint256,uint256,address)": FunctionFragment;
    "changeIssuerAndApprover(address,uint256,uint256,uint256,uint256,address)": FunctionFragment;
    "contribute(address,uint256,uint256)": FunctionFragment;
    "drainBounty(address,uint256,uint256,uint256[])": FunctionFragment;
    "fulfillAndAccept(address,uint256,address[],string,uint256,uint256[])": FunctionFragment;
    "fulfillBounty(address,uint256,address[],string)": FunctionFragment;
    "getBounty(uint256)": FunctionFragment;
    "issueAndContribute(address,address[],address[],string,uint256,address,uint256,uint256)": FunctionFragment;
    "issueBounty(address,address[],address[],string,uint256,address,uint256)": FunctionFragment;
    "metaTxRelayer()": FunctionFragment;
    "numBounties()": FunctionFragment;
    "owner()": FunctionFragment;
    "performAction(address,uint256,string)": FunctionFragment;
    "refundContribution(address,uint256,uint256)": FunctionFragment;
    "refundContributions(address,uint256,uint256,uint256[])": FunctionFragment;
    "refundMyContributions(address,uint256,uint256[])": FunctionFragment;
    "setMetaTxRelayer(address)": FunctionFragment;
    "tokenBalances(uint256,uint256)": FunctionFragment;
    "updateFulfillment(address,uint256,uint256,address[],string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptFulfillment"
      | "addApprovers"
      | "addIssuers"
      | "bounties"
      | "callStarted"
      | "changeApprover"
      | "changeBounty"
      | "changeData"
      | "changeDeadline"
      | "changeIssuer"
      | "changeIssuerAndApprover"
      | "contribute"
      | "drainBounty"
      | "fulfillAndAccept"
      | "fulfillBounty"
      | "getBounty"
      | "issueAndContribute"
      | "issueBounty"
      | "metaTxRelayer"
      | "numBounties"
      | "owner"
      | "performAction"
      | "refundContribution"
      | "refundContributions"
      | "refundMyContributions"
      | "setMetaTxRelayer"
      | "tokenBalances"
      | "updateFulfillment"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptFulfillment",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addApprovers",
    values: [string, BigNumberish, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addIssuers",
    values: [string, BigNumberish, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callStarted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeApprover",
    values: [string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeBounty",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      string[],
      string[],
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changeData",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeDeadline",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeIssuer",
    values: [string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeIssuerAndApprover",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "drainBounty",
    values: [string, BigNumberish, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillAndAccept",
    values: [
      string,
      BigNumberish,
      string[],
      string,
      BigNumberish,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillBounty",
    values: [string, BigNumberish, string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "issueAndContribute",
    values: [
      string,
      string[],
      string[],
      string,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "issueBounty",
    values: [
      string,
      string[],
      string[],
      string,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaTxRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numBounties",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performAction",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "refundContribution",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundContributions",
    values: [string, BigNumberish, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "refundMyContributions",
    values: [string, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetaTxRelayer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBalances",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFulfillment",
    values: [string, BigNumberish, BigNumberish, string[], string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addApprovers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addIssuers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callStarted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeApprover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeIssuerAndApprover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "drainBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillAndAccept",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueAndContribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaTxRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numBounties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundMyContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetaTxRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFulfillment",
    data: BytesLike
  ): Result;

  events: {
    "ActionPerformed(uint256,address,string)": EventFragment;
    "BountyApproversUpdated(uint256,address,address[])": EventFragment;
    "BountyChanged(uint256,address,address[],address[],string,uint256)": EventFragment;
    "BountyDataChanged(uint256,address,string)": EventFragment;
    "BountyDeadlineChanged(uint256,address,uint256)": EventFragment;
    "BountyDrained(uint256,address,uint256[])": EventFragment;
    "BountyFulfilled(uint256,uint256,address[],string,address)": EventFragment;
    "BountyIssued(uint256,address,address[],address[],string,uint256,address,uint256)": EventFragment;
    "BountyIssuersUpdated(uint256,address,address[])": EventFragment;
    "ContributionAdded(uint256,uint256,address,uint256)": EventFragment;
    "ContributionRefunded(uint256,uint256)": EventFragment;
    "ContributionsRefunded(uint256,address,uint256[])": EventFragment;
    "FulfillmentAccepted(uint256,uint256,address,uint256[])": EventFragment;
    "FulfillmentUpdated(uint256,uint256,address[],string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ActionPerformed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyApproversUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyDataChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyDeadlineChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyDrained"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyFulfilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyIssued"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BountyIssuersUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionsRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FulfillmentAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FulfillmentUpdated"): EventFragment;
}

export interface ActionPerformedEventObject {
  _bountyId: BigNumber;
  _fulfiller: string;
  _data: string;
}
export type ActionPerformedEvent = TypedEvent<
  [BigNumber, string, string],
  ActionPerformedEventObject
>;

export type ActionPerformedEventFilter = TypedEventFilter<ActionPerformedEvent>;

export interface BountyApproversUpdatedEventObject {
  _bountyId: BigNumber;
  _changer: string;
  _approvers: string[];
}
export type BountyApproversUpdatedEvent = TypedEvent<
  [BigNumber, string, string[]],
  BountyApproversUpdatedEventObject
>;

export type BountyApproversUpdatedEventFilter =
  TypedEventFilter<BountyApproversUpdatedEvent>;

export interface BountyChangedEventObject {
  _bountyId: BigNumber;
  _changer: string;
  _issuers: string[];
  _approvers: string[];
  _data: string;
  _deadline: BigNumber;
}
export type BountyChangedEvent = TypedEvent<
  [BigNumber, string, string[], string[], string, BigNumber],
  BountyChangedEventObject
>;

export type BountyChangedEventFilter = TypedEventFilter<BountyChangedEvent>;

export interface BountyDataChangedEventObject {
  _bountyId: BigNumber;
  _changer: string;
  _data: string;
}
export type BountyDataChangedEvent = TypedEvent<
  [BigNumber, string, string],
  BountyDataChangedEventObject
>;

export type BountyDataChangedEventFilter =
  TypedEventFilter<BountyDataChangedEvent>;

export interface BountyDeadlineChangedEventObject {
  _bountyId: BigNumber;
  _changer: string;
  _deadline: BigNumber;
}
export type BountyDeadlineChangedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  BountyDeadlineChangedEventObject
>;

export type BountyDeadlineChangedEventFilter =
  TypedEventFilter<BountyDeadlineChangedEvent>;

export interface BountyDrainedEventObject {
  _bountyId: BigNumber;
  _issuer: string;
  _amounts: BigNumber[];
}
export type BountyDrainedEvent = TypedEvent<
  [BigNumber, string, BigNumber[]],
  BountyDrainedEventObject
>;

export type BountyDrainedEventFilter = TypedEventFilter<BountyDrainedEvent>;

export interface BountyFulfilledEventObject {
  _bountyId: BigNumber;
  _fulfillmentId: BigNumber;
  _fulfillers: string[];
  _data: string;
  _submitter: string;
}
export type BountyFulfilledEvent = TypedEvent<
  [BigNumber, BigNumber, string[], string, string],
  BountyFulfilledEventObject
>;

export type BountyFulfilledEventFilter = TypedEventFilter<BountyFulfilledEvent>;

export interface BountyIssuedEventObject {
  _bountyId: BigNumber;
  _creator: string;
  _issuers: string[];
  _approvers: string[];
  _data: string;
  _deadline: BigNumber;
  _token: string;
  _tokenVersion: BigNumber;
}
export type BountyIssuedEvent = TypedEvent<
  [BigNumber, string, string[], string[], string, BigNumber, string, BigNumber],
  BountyIssuedEventObject
>;

export type BountyIssuedEventFilter = TypedEventFilter<BountyIssuedEvent>;

export interface BountyIssuersUpdatedEventObject {
  _bountyId: BigNumber;
  _changer: string;
  _issuers: string[];
}
export type BountyIssuersUpdatedEvent = TypedEvent<
  [BigNumber, string, string[]],
  BountyIssuersUpdatedEventObject
>;

export type BountyIssuersUpdatedEventFilter =
  TypedEventFilter<BountyIssuersUpdatedEvent>;

export interface ContributionAddedEventObject {
  _bountyId: BigNumber;
  _contributionId: BigNumber;
  _contributor: string;
  _amount: BigNumber;
}
export type ContributionAddedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber],
  ContributionAddedEventObject
>;

export type ContributionAddedEventFilter =
  TypedEventFilter<ContributionAddedEvent>;

export interface ContributionRefundedEventObject {
  _bountyId: BigNumber;
  _contributionId: BigNumber;
}
export type ContributionRefundedEvent = TypedEvent<
  [BigNumber, BigNumber],
  ContributionRefundedEventObject
>;

export type ContributionRefundedEventFilter =
  TypedEventFilter<ContributionRefundedEvent>;

export interface ContributionsRefundedEventObject {
  _bountyId: BigNumber;
  _issuer: string;
  _contributionIds: BigNumber[];
}
export type ContributionsRefundedEvent = TypedEvent<
  [BigNumber, string, BigNumber[]],
  ContributionsRefundedEventObject
>;

export type ContributionsRefundedEventFilter =
  TypedEventFilter<ContributionsRefundedEvent>;

export interface FulfillmentAcceptedEventObject {
  _bountyId: BigNumber;
  _fulfillmentId: BigNumber;
  _approver: string;
  _tokenAmounts: BigNumber[];
}
export type FulfillmentAcceptedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber[]],
  FulfillmentAcceptedEventObject
>;

export type FulfillmentAcceptedEventFilter =
  TypedEventFilter<FulfillmentAcceptedEvent>;

export interface FulfillmentUpdatedEventObject {
  _bountyId: BigNumber;
  _fulfillmentId: BigNumber;
  _fulfillers: string[];
  _data: string;
}
export type FulfillmentUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, string[], string],
  FulfillmentUpdatedEventObject
>;

export type FulfillmentUpdatedEventFilter =
  TypedEventFilter<FulfillmentUpdatedEvent>;

export interface TestContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptFulfillment(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillmentId: BigNumberish,
      _approverId: BigNumberish,
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addApprovers(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _approvers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addIssuers(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bounties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber, boolean] & {
        deadline: BigNumber;
        token: string;
        tokenVersion: BigNumber;
        balance: BigNumber;
        hasPaidOut: boolean;
      }
    >;

    callStarted(overrides?: CallOverrides): Promise<[boolean]>;

    changeApprover(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _approverId: BigNumberish,
      _approver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeData(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeDeadline(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeIssuer(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuerIdToChange: BigNumberish,
      _newIssuer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeIssuerAndApprover(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuerIdToChange: BigNumberish,
      _approverIdToChange: BigNumberish,
      _issuer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    contribute(
      _sender: string,
      _bountyId: BigNumberish,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    drainBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fulfillAndAccept(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      _approverId: BigNumberish,
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fulfillBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getBounty(
      _bountyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[StandardBounties.BountyStructOutput]>;

    issueAndContribute(
      _sender: string,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      _token: string,
      _tokenVersion: BigNumberish,
      _depositAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    issueBounty(
      _sender: string,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      _token: string,
      _tokenVersion: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    metaTxRelayer(overrides?: CallOverrides): Promise<[string]>;

    numBounties(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    performAction(
      _sender: string,
      _bountyId: BigNumberish,
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    refundContribution(
      _sender: string,
      _bountyId: BigNumberish,
      _contributionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    refundContributions(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _contributionIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    refundMyContributions(
      _sender: string,
      _bountyId: BigNumberish,
      _contributionIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMetaTxRelayer(
      _relayer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenBalances(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    updateFulfillment(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillmentId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptFulfillment(
    _sender: string,
    _bountyId: BigNumberish,
    _fulfillmentId: BigNumberish,
    _approverId: BigNumberish,
    _tokenAmounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addApprovers(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _approvers: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addIssuers(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _issuers: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bounties(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, BigNumber, boolean] & {
      deadline: BigNumber;
      token: string;
      tokenVersion: BigNumber;
      balance: BigNumber;
      hasPaidOut: boolean;
    }
  >;

  callStarted(overrides?: CallOverrides): Promise<boolean>;

  changeApprover(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _approverId: BigNumberish,
    _approver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeBounty(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _issuers: string[],
    _approvers: string[],
    _data: string,
    _deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeData(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _data: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeDeadline(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeIssuer(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _issuerIdToChange: BigNumberish,
    _newIssuer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeIssuerAndApprover(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _issuerIdToChange: BigNumberish,
    _approverIdToChange: BigNumberish,
    _issuer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  contribute(
    _sender: string,
    _bountyId: BigNumberish,
    _amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  drainBounty(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _amounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fulfillAndAccept(
    _sender: string,
    _bountyId: BigNumberish,
    _fulfillers: string[],
    _data: string,
    _approverId: BigNumberish,
    _tokenAmounts: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fulfillBounty(
    _sender: string,
    _bountyId: BigNumberish,
    _fulfillers: string[],
    _data: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getBounty(
    _bountyId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<StandardBounties.BountyStructOutput>;

  issueAndContribute(
    _sender: string,
    _issuers: string[],
    _approvers: string[],
    _data: string,
    _deadline: BigNumberish,
    _token: string,
    _tokenVersion: BigNumberish,
    _depositAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  issueBounty(
    _sender: string,
    _issuers: string[],
    _approvers: string[],
    _data: string,
    _deadline: BigNumberish,
    _token: string,
    _tokenVersion: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  metaTxRelayer(overrides?: CallOverrides): Promise<string>;

  numBounties(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  performAction(
    _sender: string,
    _bountyId: BigNumberish,
    _data: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  refundContribution(
    _sender: string,
    _bountyId: BigNumberish,
    _contributionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  refundContributions(
    _sender: string,
    _bountyId: BigNumberish,
    _issuerId: BigNumberish,
    _contributionIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  refundMyContributions(
    _sender: string,
    _bountyId: BigNumberish,
    _contributionIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMetaTxRelayer(
    _relayer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenBalances(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  updateFulfillment(
    _sender: string,
    _bountyId: BigNumberish,
    _fulfillmentId: BigNumberish,
    _fulfillers: string[],
    _data: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptFulfillment(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillmentId: BigNumberish,
      _approverId: BigNumberish,
      _tokenAmounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    addApprovers(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _approvers: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    addIssuers(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuers: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    bounties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber, boolean] & {
        deadline: BigNumber;
        token: string;
        tokenVersion: BigNumber;
        balance: BigNumber;
        hasPaidOut: boolean;
      }
    >;

    callStarted(overrides?: CallOverrides): Promise<boolean>;

    changeApprover(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _approverId: BigNumberish,
      _approver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeData(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _data: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeDeadline(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    changeIssuer(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuerIdToChange: BigNumberish,
      _newIssuer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeIssuerAndApprover(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuerIdToChange: BigNumberish,
      _approverIdToChange: BigNumberish,
      _issuer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    contribute(
      _sender: string,
      _bountyId: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    drainBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _amounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    fulfillAndAccept(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      _approverId: BigNumberish,
      _tokenAmounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    fulfillBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getBounty(
      _bountyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<StandardBounties.BountyStructOutput>;

    issueAndContribute(
      _sender: string,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      _token: string,
      _tokenVersion: BigNumberish,
      _depositAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    issueBounty(
      _sender: string,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      _token: string,
      _tokenVersion: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metaTxRelayer(overrides?: CallOverrides): Promise<string>;

    numBounties(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    performAction(
      _sender: string,
      _bountyId: BigNumberish,
      _data: string,
      overrides?: CallOverrides
    ): Promise<void>;

    refundContribution(
      _sender: string,
      _bountyId: BigNumberish,
      _contributionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    refundContributions(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _contributionIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    refundMyContributions(
      _sender: string,
      _bountyId: BigNumberish,
      _contributionIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    setMetaTxRelayer(
      _relayer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenBalances(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateFulfillment(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillmentId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ActionPerformed(uint256,address,string)"(
      _bountyId?: null,
      _fulfiller?: null,
      _data?: null
    ): ActionPerformedEventFilter;
    ActionPerformed(
      _bountyId?: null,
      _fulfiller?: null,
      _data?: null
    ): ActionPerformedEventFilter;

    "BountyApproversUpdated(uint256,address,address[])"(
      _bountyId?: null,
      _changer?: null,
      _approvers?: null
    ): BountyApproversUpdatedEventFilter;
    BountyApproversUpdated(
      _bountyId?: null,
      _changer?: null,
      _approvers?: null
    ): BountyApproversUpdatedEventFilter;

    "BountyChanged(uint256,address,address[],address[],string,uint256)"(
      _bountyId?: null,
      _changer?: null,
      _issuers?: null,
      _approvers?: null,
      _data?: null,
      _deadline?: null
    ): BountyChangedEventFilter;
    BountyChanged(
      _bountyId?: null,
      _changer?: null,
      _issuers?: null,
      _approvers?: null,
      _data?: null,
      _deadline?: null
    ): BountyChangedEventFilter;

    "BountyDataChanged(uint256,address,string)"(
      _bountyId?: null,
      _changer?: null,
      _data?: null
    ): BountyDataChangedEventFilter;
    BountyDataChanged(
      _bountyId?: null,
      _changer?: null,
      _data?: null
    ): BountyDataChangedEventFilter;

    "BountyDeadlineChanged(uint256,address,uint256)"(
      _bountyId?: null,
      _changer?: null,
      _deadline?: null
    ): BountyDeadlineChangedEventFilter;
    BountyDeadlineChanged(
      _bountyId?: null,
      _changer?: null,
      _deadline?: null
    ): BountyDeadlineChangedEventFilter;

    "BountyDrained(uint256,address,uint256[])"(
      _bountyId?: null,
      _issuer?: null,
      _amounts?: null
    ): BountyDrainedEventFilter;
    BountyDrained(
      _bountyId?: null,
      _issuer?: null,
      _amounts?: null
    ): BountyDrainedEventFilter;

    "BountyFulfilled(uint256,uint256,address[],string,address)"(
      _bountyId?: null,
      _fulfillmentId?: null,
      _fulfillers?: null,
      _data?: null,
      _submitter?: null
    ): BountyFulfilledEventFilter;
    BountyFulfilled(
      _bountyId?: null,
      _fulfillmentId?: null,
      _fulfillers?: null,
      _data?: null,
      _submitter?: null
    ): BountyFulfilledEventFilter;

    "BountyIssued(uint256,address,address[],address[],string,uint256,address,uint256)"(
      _bountyId?: null,
      _creator?: null,
      _issuers?: null,
      _approvers?: null,
      _data?: null,
      _deadline?: null,
      _token?: null,
      _tokenVersion?: null
    ): BountyIssuedEventFilter;
    BountyIssued(
      _bountyId?: null,
      _creator?: null,
      _issuers?: null,
      _approvers?: null,
      _data?: null,
      _deadline?: null,
      _token?: null,
      _tokenVersion?: null
    ): BountyIssuedEventFilter;

    "BountyIssuersUpdated(uint256,address,address[])"(
      _bountyId?: null,
      _changer?: null,
      _issuers?: null
    ): BountyIssuersUpdatedEventFilter;
    BountyIssuersUpdated(
      _bountyId?: null,
      _changer?: null,
      _issuers?: null
    ): BountyIssuersUpdatedEventFilter;

    "ContributionAdded(uint256,uint256,address,uint256)"(
      _bountyId?: null,
      _contributionId?: null,
      _contributor?: null,
      _amount?: null
    ): ContributionAddedEventFilter;
    ContributionAdded(
      _bountyId?: null,
      _contributionId?: null,
      _contributor?: null,
      _amount?: null
    ): ContributionAddedEventFilter;

    "ContributionRefunded(uint256,uint256)"(
      _bountyId?: null,
      _contributionId?: null
    ): ContributionRefundedEventFilter;
    ContributionRefunded(
      _bountyId?: null,
      _contributionId?: null
    ): ContributionRefundedEventFilter;

    "ContributionsRefunded(uint256,address,uint256[])"(
      _bountyId?: null,
      _issuer?: null,
      _contributionIds?: null
    ): ContributionsRefundedEventFilter;
    ContributionsRefunded(
      _bountyId?: null,
      _issuer?: null,
      _contributionIds?: null
    ): ContributionsRefundedEventFilter;

    "FulfillmentAccepted(uint256,uint256,address,uint256[])"(
      _bountyId?: null,
      _fulfillmentId?: null,
      _approver?: null,
      _tokenAmounts?: null
    ): FulfillmentAcceptedEventFilter;
    FulfillmentAccepted(
      _bountyId?: null,
      _fulfillmentId?: null,
      _approver?: null,
      _tokenAmounts?: null
    ): FulfillmentAcceptedEventFilter;

    "FulfillmentUpdated(uint256,uint256,address[],string)"(
      _bountyId?: null,
      _fulfillmentId?: null,
      _fulfillers?: null,
      _data?: null
    ): FulfillmentUpdatedEventFilter;
    FulfillmentUpdated(
      _bountyId?: null,
      _fulfillmentId?: null,
      _fulfillers?: null,
      _data?: null
    ): FulfillmentUpdatedEventFilter;
  };

  estimateGas: {
    acceptFulfillment(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillmentId: BigNumberish,
      _approverId: BigNumberish,
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addApprovers(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _approvers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addIssuers(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bounties(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    callStarted(overrides?: CallOverrides): Promise<BigNumber>;

    changeApprover(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _approverId: BigNumberish,
      _approver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeData(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeDeadline(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeIssuer(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuerIdToChange: BigNumberish,
      _newIssuer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeIssuerAndApprover(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuerIdToChange: BigNumberish,
      _approverIdToChange: BigNumberish,
      _issuer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    contribute(
      _sender: string,
      _bountyId: BigNumberish,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    drainBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fulfillAndAccept(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      _approverId: BigNumberish,
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fulfillBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getBounty(
      _bountyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    issueAndContribute(
      _sender: string,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      _token: string,
      _tokenVersion: BigNumberish,
      _depositAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    issueBounty(
      _sender: string,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      _token: string,
      _tokenVersion: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    metaTxRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    numBounties(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    performAction(
      _sender: string,
      _bountyId: BigNumberish,
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    refundContribution(
      _sender: string,
      _bountyId: BigNumberish,
      _contributionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    refundContributions(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _contributionIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    refundMyContributions(
      _sender: string,
      _bountyId: BigNumberish,
      _contributionIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMetaTxRelayer(
      _relayer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenBalances(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateFulfillment(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillmentId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptFulfillment(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillmentId: BigNumberish,
      _approverId: BigNumberish,
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addApprovers(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _approvers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addIssuers(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bounties(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    callStarted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeApprover(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _approverId: BigNumberish,
      _approver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeData(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeDeadline(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeIssuer(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuerIdToChange: BigNumberish,
      _newIssuer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeIssuerAndApprover(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _issuerIdToChange: BigNumberish,
      _approverIdToChange: BigNumberish,
      _issuer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    contribute(
      _sender: string,
      _bountyId: BigNumberish,
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    drainBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _amounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fulfillAndAccept(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      _approverId: BigNumberish,
      _tokenAmounts: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fulfillBounty(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getBounty(
      _bountyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    issueAndContribute(
      _sender: string,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      _token: string,
      _tokenVersion: BigNumberish,
      _depositAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    issueBounty(
      _sender: string,
      _issuers: string[],
      _approvers: string[],
      _data: string,
      _deadline: BigNumberish,
      _token: string,
      _tokenVersion: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    metaTxRelayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numBounties(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    performAction(
      _sender: string,
      _bountyId: BigNumberish,
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    refundContribution(
      _sender: string,
      _bountyId: BigNumberish,
      _contributionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    refundContributions(
      _sender: string,
      _bountyId: BigNumberish,
      _issuerId: BigNumberish,
      _contributionIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    refundMyContributions(
      _sender: string,
      _bountyId: BigNumberish,
      _contributionIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMetaTxRelayer(
      _relayer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenBalances(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateFulfillment(
      _sender: string,
      _bountyId: BigNumberish,
      _fulfillmentId: BigNumberish,
      _fulfillers: string[],
      _data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
